name: CI
on: [push,workflow_dispatch]
jobs:
  build:
    env:
      docker_user: ${{ secrets.DOCKER_USER }}
      docker_pass: ${{ secrets.DOCKER_PASS }}
    runs-on: ubuntu-latest
    steps:
        - name: get code
          uses: actions/checkout@v3
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Cache Docker Layers
          uses: actions/cache@v4
          with:
            path: /tmp/buildx-cache
            key: ${{ runner.os }}-buildx-${{ github.sha }}
            restore-keys:
              ${{ runner.os }}-buildx-
        - name: docker build
          run: docker build -t roeyzalta/github-actions-test:${{ github.sha }} .
        - name: docker login
          run: docker login -u ${{ env.docker_user }} -p ${{ env.docker_pass }}
        - name: docker push
          run: docker push roeyzalta/github-actions-test:${{ github.sha }}