name: CI
on: [push,workflow_dispatch]
jobs:
  test:
    env:
      MONGODB_CLUSTER_ADDRESS: ${{ vars.MONGODB_CLUSTER_ADDRESS }}
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        run: npm ci 
      # - name: Run Server
      #   run: npm start & npx wait-on http://127.0.0.1:$PORT
      # - name: run TESTS
      #   run: npm test
      - name: Output Information
        run: |
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
  deploy:
    env:
      MONGODB_DB_NAME: ${{ vars.MONGODB_DB_NAME }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output Information
        run: |
          echo "MONGODB_USERNAME: ${{ steps.test.env.MONGODB_USERNAME }}"
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
